name: JackLMcClure
favicon: null
layout_spectrum: 0.49856
typography_spectrum: 0.14007
title: Jack L McClure
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d2e3f3'
    - '#2c445e'
    - '#5e90b5'
    - '#9ac1c6'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
